### ISSUE TITLE
How to set __index metatable on userdata to table with methods?

### ISSUE THREAD

**Issue by mkpankov** [tomaka/hlua#137]
I'm trying to implement object-oriented access to my custom type like [described here](https://www.lua.org/pil/28.3.html). I want to be able to do `foo:bar(args)` in Lua, where `bar` is a Rust function and `foo` is userdata.

I thought I could set `__index` like so:

```rust
implement_lua_push!(SerialPortLua, |mut metatable| {
    metatable.set("__index", XXX);
});
```

but the problem is `metatable.set` accepts a `hlua::function`, not `hlua::LuaTable`.

Is there any other way? Maybe I'm missing something and index metatable should be set differently?

**Comment by tomaka** [comment]
You're supposed to call `metatable.empty_array("__index")`, which will return a `LuaTable` which you can then fill.

**Comment by mkpankov** [comment]
Thanks!
