### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sid0** [tomaka/hlua#157]
Hi -- are there any plans to do a new release any time soon? From a quick eyeball it looks like there are a bunch of incompatibilities, so I guess the release will be 0.4.0.

**Comment by sid0** [comment]
(It would also be helpful if releases to crates.io were tagged and pushed to GH :) )

**Comment by sid0** [comment]
Hi -- looks like this wasn't published to crates.io. Any chance you could get it up there as well? Thanks!

**Comment by tomaka** [comment]
Oh that's because it needs a bump in lua52-sys.
