### ISSUE TITLE
Can't compile lua52-sys

### ISSUE THREAD

**Issue by TyOverby** [tomaka/hlua#38]
``` 
failed to run custom build command for `lua52-sys v0.0.2`
Process didn't exit successfully: `/Users/tyoverby/workspace/rust/hlua-test/target/build/lua52-sys-c513186a8dc2f8d8/build-script-build` (status=101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"lua5.2\"`: No such file or directory (os error 2)"', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:744
```

**Comment by tomaka** [comment]
It probably can't find pkg-config.
You can override the build script: http://doc.crates.io/build-script.html#overriding-build-scripts

**Comment by TyOverby** [comment]
Lua is really easy to build from scratch.  Would you consider doing what I did in [chipmunk-sys](https://github.com/TyOverby/chipmunk-sys) and just compile the entire library and statically link against it?

As you can see, the [build file](https://github.com/TyOverby/chipmunk-sys/blob/master/build.rs) is really simple.
