### ISSUE TITLE
Compile broken with nightly rustc

### ISSUE THREAD

**Issue by MarkSwanson** [tomaka/hlua#48]
hlua-0.1.3/src/functions_read.rs:5:5: 5:24 error: unresolved import `std::ffi::IntoBytes`. There is no `IntoBytes` in `std::ffi`

It would be fun to play with rust/lua.
Thanks.

**Comment by tomaka** [comment]
Ah! I forgot to publish a new version on crates.io.
This should be good in a few minutes.

**Comment by MarkSwanson** [comment]
Thanks!
