### ISSUE TITLE
doc bugs

### ISSUE THREAD

**Issue by MarkSwanson** [tomaka/hlua#49]
Minor issues, but I am having some trouble getting the examples to work as described in the README.md:

- use hlua;  
  is required

-         lua.execute("x = x + 1").unwrap();
   error: unable to infer enough type information about `_`; type annotations required [E0282]

-  let get_five: hlua::functions_read::LuaFunction = lua.get("get_five").unwrap();
  error: wrong number of type arguments: expected 1, found 0 [E0243]

I'm on the April 25th nightly. I'm hoping I'm new enough and any nightly will also see these problems.

**Comment by Ediacarium** [comment]
Hi i had the same problem.

For anyone stumbling upon this:
This works:

`let y: () = lua.execute("x=x + 1").unwrap();`

there might be a better way to do this without using a variable, but it works for the moment.

**Comment by tomaka** [comment]
Fixed by #56
