### ISSUE TITLE
Crates.io doesn't have the latest version

### ISSUE THREAD

**Issue by Ameliorate** [tomaka/hlua#71]
In the commit a6fe3081d98b8f6c1035001582144b502d897565, 0.1.8 is released, however the crates.io package at https://crates.io/crates/hlua/ only has 0.1.7.

**Comment by Ameliorate** [comment]
For now, this can be worked around with https://crates.io/crates/hlua_master

**Comment by tomaka** [comment]
Fixed by #70 which I had forgotten to merge
