### ISSUE TITLE
Why does implement_lua_read!(...) not implement everything you need?

### ISSUE THREAD

**Issue by CryZe** [tomaka/hlua#75]
If you want to have functions that take 2 or more parameters with one of them being a user data type, it won't work as the impls for it are missing, so you need to write additional impls:
![http://puu.sh/oSHM3.png](http://puu.sh/oSHM3.png)

This seems weird. Am I missing something or why is this the case?

Looks like this doesn't even work, so I don't know what to do now :/

This is the error I'm getting:
![http://puu.sh/oSInR.png](http://puu.sh/oSInR.png)

**Comment by tomaka** [comment]
This macro was hastily written. This may be a legitimate mistake.

**Comment by CryZe** [comment]
Is there a way for me to fix this?

**Comment by CryZe** [comment]
Looks like the index parameter provided is -2, which fails the assertion in [userdata::read_userdata](https://github.com/tomaka/hlua/blob/master/hlua/src/userdata.rs#L102)

**Comment by CryZe** [comment]
The argument count of 2 causes the index to be -2
![http://puu.sh/oTSAv.png](http://puu.sh/oTSAv.png)
