### ISSUE TITLE
Closures can outlive their environments

### ISSUE THREAD

**Issue by CryZe** [tomaka/hlua#77]
All the hlua::functionxx functions take closures that can outlive their environments and cause Segfaults and all kinds of other corruptions as can be seen in this video: https://youtu.be/-0oMsyXZtwA

**Comment by tomaka** [comment]
Unfortunately I have no idea how to fix that.

Hlua's code is basically `impl<C, L> Push<L> for C where L: Lua, C: FnMut() -> ()`.
I don't see how to enforce the fact that `C` must outlive `L`.

**Comment by CryZe** [comment]
Maybe force them to have a static lifetime, just like threads do? Not sure
if that's possible.

tomaka <notifications@github.com> schrieb am Do. 22. Dez. 2016 um 14:21:
